using do_an_tot_nghiep.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace do_an_tot_nghiep.Controllers.Api
{
    /// <summary>
    /// Quản lý phòng trọ.
    /// </summary>
    [ApiController]
    [Route("api/phongtro")]
    public class PhongTroApiController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public PhongTroApiController(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Danh sách phòng.
        /// </summary>
        [HttpGet]
        public async Task<ActionResult<List<PhongTro>>> GetAll()
        {
            var rooms = await _context.PhongTros.Where(p => !p.IsDeleted).ToListAsync();
            var roomIds = rooms.Select(r => r.Id).ToList();
            var thumbs = await _context.Images
                .Where(i => i.RoomId != null && roomIds.Contains(i.RoomId.Value) && i.IsThumbnail)
                .ToListAsync();

            foreach (var r in rooms)
            {
                var t = thumbs.FirstOrDefault(x => x.RoomId == r.Id);
                if (t != null) r.AnhPhong = t.ImageUrl;
            }
            return rooms;
        }

        /// <summary>
        /// Lấy phòng theo id.
        /// </summary>
        [HttpGet("{id:int}")]
        public async Task<ActionResult<PhongTro>> GetById(int id)
        {
            var phong = await _context.PhongTros.FindAsync(id);
            if (phong == null || phong.IsDeleted) return NotFound();

            var thumb = await _context.Images.FirstOrDefaultAsync(i => i.RoomId == id && i.IsThumbnail);
            if (thumb != null) phong.AnhPhong = thumb.ImageUrl;

            return phong;
        }

        /// <summary>
        /// Tạo phòng mới.
        /// </summary>
        [HttpPost]
        public async Task<ActionResult<PhongTro>> Create(PhongTro phong)
        {
            if (string.IsNullOrWhiteSpace(phong.DoiTuong))
            {
                phong.DoiTuong = "Standard";
            }
            phong.Status = 1; // Default to Vacant
            _context.PhongTros.Add(phong);

            // Log the initial state
            _context.RoomStatusHistories.Add(new RoomStatusHistory
            {
                PhongTro = phong,
                OldStatus = 1,
                NewStatus = 1,
                Reason = "Khởi tạo phòng mới",
                AutoGenerated = true
            });

            await _context.SaveChangesAsync();
            return CreatedAtAction(nameof(GetById), new { id = phong.Id }, phong);
        }

        /// <summary>
        /// Cập nhật phòng.
        /// </summary>
        [HttpPut("{id:int}")]
        public async Task<IActionResult> Update(int id, PhongTro phong)
        {
            if (id != phong.Id) return BadRequest();

            var existing = await _context.PhongTros.FindAsync(id);
            if (existing == null || existing.IsDeleted) return NotFound();

            // Check if there's any active contract
            var activeContract = await _context.HopDongs
                .Include(h => h.HopDongKhachThues)
                .FirstOrDefaultAsync(h => h.PhongTroId == id && h.TrangThai == TrangThaiHopDong.DangHieuLuc);

            if (activeContract != null)
            {
                // BR-R2: Không cho sửa RoomCode (TenPhong) nếu đã có hợp đồng
                if (existing.TenPhong != phong.TenPhong)
                    return BadRequest(new { message = "Không thể sửa Mã phòng vì đang có hợp đồng Active." });

                // BR-R3: Không giảm MaxOccupants < số cư dân đang ở
                int currentTenants = activeContract.HopDongKhachThues.Count;
                if (phong.SoLuongNguoi < currentTenants)
                    return BadRequest(new { message = $"Không thể giảm số lượng người tối đa ({phong.SoLuongNguoi}) thấp hơn số người đang ở thực tế ({currentTenants})." });
            }

            if (string.IsNullOrWhiteSpace(phong.DoiTuong))
            {
                phong.DoiTuong = "Standard";
            }

            // DO NOT update Status directly. Handled by State Machine.
            // DO NOT use SetValues to avoid overwriting CreatedAt, IsDeleted etc.

            existing.TenPhong = phong.TenPhong;
            existing.Tang = phong.Tang;
            existing.GiaPhong = phong.GiaPhong;
            existing.DienTich = phong.DienTich;
            existing.SoLuongNguoi = phong.SoLuongNguoi;
            existing.DoiTuong = phong.DoiTuong;
            existing.DichVu = phong.DichVu;

            // New Safe Zone properties
            existing.ConditionScore = phong.ConditionScore;
            existing.Balcony = phong.Balcony;
            existing.HasPrivateBathroom = phong.HasPrivateBathroom;
            existing.Orientation = phong.Orientation;
            existing.NoiseLevelRating = phong.NoiseLevelRating;
            existing.LastInspectionDate = phong.LastInspectionDate;

            await _context.SaveChangesAsync();
            return NoContent();
        }

        /// <summary>
        /// Xóa phòng.
        /// </summary>
        [HttpDelete("{id:int}")]
        public async Task<IActionResult> Delete(int id)
        {
            var phong = await _context.PhongTros.FindAsync(id);
            if (phong == null || phong.IsDeleted) return NotFound();

            bool hasActiveContract = await _context.HopDongs
                .AnyAsync(h => h.PhongTroId == id && h.TrangThai == TrangThaiHopDong.DangHieuLuc);

            if (hasActiveContract)
                return BadRequest(new { message = "Không thể xóa phòng đang có hợp đồng Active." });

            bool hasAssets = await _context.RoomAssets.AnyAsync(ra => ra.RoomId == id);
            if (hasAssets)
                return BadRequest(new { message = "Không thể xóa phòng vì phòng đang có tài sản (Asset) chưa thanh lý." });

            phong.IsDeleted = true;
            _context.Entry(phong).State = EntityState.Modified;
            await _context.SaveChangesAsync();
            return NoContent();
        }
    }
}
