using do_an_tot_nghiep.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace do_an_tot_nghiep.Controllers.Api
{
    [ApiController]
    [Route("api/room-status")]
    public class RoomStatusApiController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public RoomStatusApiController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet("{roomId}")]
        public async Task<IActionResult> GetTimeline(int roomId)
        {
            var history = await _context.RoomStatusHistories
                .Where(h => h.RoomId == roomId)
                .OrderByDescending(h => h.ChangedAt)
                .Select(h => new
                {
                    id = h.Id,
                    oldStatus = h.OldStatus,
                    newStatus = h.NewStatus,
                    changedAt = h.ChangedAt,
                    reason = h.Reason,
                    note = h.Note,
                    durationDays = h.DurationDays,
                    autoGenerated = h.AutoGenerated
                })
                .ToListAsync();

            return Ok(history);
        }

        // Internal/protected method for transitioning room status. Best called via Services layer.
        [HttpPost("transition")]
        public async Task<IActionResult> TransitionRoomStatus([FromBody] TransitionRequest req)
        {
            var room = await _context.PhongTros.FindAsync(req.RoomId);
            if (room == null || room.IsDeleted) return NotFound("Room not found");

            // Validate sequence
            // Vacant(1) -> Occupied(2) -> Maintenance(3)

            byte oldStatus = room.Status;

            if (oldStatus == req.NewStatus)
            {
                return BadRequest("Room is already in the requested status.");
            }

            // Allow 1 -> 2 (Contract), 2 -> 1 (Terminate), 2 -> 3 (Maintenance), 3 -> 1 (Fixed)
            bool isValid = (oldStatus == 1 && req.NewStatus == 2) ||
                           (oldStatus == 2 && req.NewStatus == 1) ||
                           (oldStatus == 2 && req.NewStatus == 3) ||
                           (oldStatus == 1 && req.NewStatus == 3) ||
                           (oldStatus == 3 && req.NewStatus == 1);

            if (!isValid)
            {
                return BadRequest($"Invalid status transition from {oldStatus} to {req.NewStatus}");
            }

            // BR-S3: Không chuyển Occupied -> Vacant nếu hợp đồng chưa kết thúc
            if (oldStatus == 2 && req.NewStatus == 1)
            {
                var activeContract = await _context.HopDongs
                    .AnyAsync(h => h.PhongTroId == req.RoomId && h.TrangThai == TrangThaiHopDong.DangHieuLuc);
                if (activeContract)
                {
                    return BadRequest("Không thể chuyển phòng sang trạng thái Trống (Vacant) vì đang có hợp đồng Active.");
                }
            }

            // Calculate duration if applicable
            var lastHistory = await _context.RoomStatusHistories
                 .Where(h => h.RoomId == req.RoomId)
                 .OrderByDescending(h => h.ChangedAt)
                 .FirstOrDefaultAsync();

            int? days = null;
            if (lastHistory != null)
            {
                days = (int)(DateTime.UtcNow - lastHistory.ChangedAt).TotalDays;

                // Update previous log duration
                lastHistory.DurationDays = days;
                _context.Entry(lastHistory).State = EntityState.Modified;
            }

            room.Status = req.NewStatus;

            var log = new RoomStatusHistory
            {
                RoomId = room.Id,
                OldStatus = oldStatus,
                NewStatus = req.NewStatus,
                ChangedAt = DateTime.UtcNow,
                Reason = req.Reason,
                Note = req.Note,
                AutoGenerated = req.AutoGenerated
            };

            _context.RoomStatusHistories.Add(log);
            _context.Entry(room).State = EntityState.Modified;

            await _context.SaveChangesAsync();
            return Ok();
        }
    }

    public class TransitionRequest
    {
        public int RoomId { get; set; }
        public byte NewStatus { get; set; }
        public string Reason { get; set; } = string.Empty;
        public string? Note { get; set; }
        public bool AutoGenerated { get; set; } = true;
    }
}
