using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace do_an_tot_nghiep.Models
{
    [Table("RoomStatusHistories")]
    public class RoomStatusHistory
    {
        [Key]
        [Column("HistoryId")]
        public int Id { get; set; }

        [Required]
        public int RoomId { get; set; }

        [ForeignKey("RoomId")]
        public PhongTro? PhongTro { get; set; }

        [Required]
        public byte OldStatus { get; set; } = 1;

        [Required]
        public byte NewStatus { get; set; } = 1;

        public DateTime ChangedAt { get; set; } = DateTime.UtcNow;

        [MaxLength(255)]
        public string? Reason { get; set; }

        public string? Note { get; set; }
        public int? DurationDays { get; set; }
        public bool AutoGenerated { get; set; } = false;

        public int? ChangedByUserId { get; set; }
    }
}
